version: '3.3'
services:
    noted:
        container_name: noted
        volumes:
            - 'noted-db:/app/db'
        environment:
            - TZ=Europe/Amsterdam
        ports:
            - '8080:8080'
        image: 'mrcas/noted:latest'
