version: '3.3'
services:
    mind:
        container_name: mind
        volumes:
            - 'mind-db:/app/db'
        environment:
            - TZ=Europe/Amsterdam
        ports:
            - '8080:8080'
        image: 'mrcas/mind:latest'
