services:
  mind:
    container_name: mind
    image: mrcas/mind:latest
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
    volumes:
      - "mind-db:/app/db"
    ports:
      - 8080:8080

volumes:
  mind-db: