# Site Details
site_name: MIND Docs
site_description: The official guide for MIND 
site_author: Casvt
repo_url: https://github.com/Casvt/MIND
edit_uri: blob/Development/docs/
repo_name: Casvt/MIND
docs_dir: ../docs

extra_css:
  - assets/css/extra.css

# Site appearance (logos, colours, icons)
theme:
  name: material
  language: en
  code_wrap: true
  features:
    - content.tabs.link
    - content.code.copy
    - header.autohide
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
  favicon: assets/img/favicon.svg
  logo: assets/img/favicon.svg
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: MIND
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: MIND-dark
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Markdown extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - meta
  - pymdownx.details
  - pymdownx.highlight:
      guess_lang: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - sane_lists
  - toc:
      permalink: true
      toc_depth: 3
  - tables

# mkdocs function extensions
plugins:
  - search
  - git-revision-date-localized:
      type: timeago
      locale: en
      fallback_to_build_date: false

# Navigation Layout
nav:
  - Home: index.md
  - Installation And Updating:
    - Introduction: installation/installation.md
    - Docker: installation/docker.md
    - Manual Instal: installation/manual_instal.md
    - Setup After Installation: installation/setup_after_installation.md
  - General Information:
    - Introduction: general_info/workings.md
    - Reminders: general_info/reminders.md
    - Admin Panel: general_info/admin_panel.md
  - Settings:
    - Introduction: settings/settings.md
    - User Settings: settings/user_settings.md
    - Admin Settings: settings/admin_settings.md
  - Other Docs:
    - Reporting: other_docs/reporting.md
    - API: other_docs/api.md
