name: Update and build docs

on:
  push:
    branches:
      - Development

jobs:
  update:
    name: Update API docs
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: python3 project_management/generate_api_docs.py

  deploy:
    needs: update
    name: Build docs
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: 'pip'
      - run: pip install -r project_management/docs-requirements.txt
      - run: mkdocs gh-deploy --force -f project_management/mkdocs.yml
