name: Tests

on:
  push:
    branches:
      - Development

jobs:
  p3.7:
    name: Python 3.7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - run: pip install -r requirements.txt
      - run: python3 -m unittest discover -s ./tests -p '*.py'

  p3.8:
    name: Python 3.8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install -r requirements.txt
      - run: python3 -m unittest discover -s ./tests -p '*.py'

  p3.9:
    name: Python 3.9
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install -r requirements.txt
      - run: python3 -m unittest discover -s ./tests -p '*.py'

  p3.10:
    name: Python 3.10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - run: pip install -r requirements.txt
      - run: python3 -m unittest discover -s ./tests -p '*.py'

  p3.11:
    name: Python 3.11
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - run: pip install -r requirements.txt
      - run: python3 -m unittest discover -s ./tests -p '*.py'
